venueGroupings = {'CRYPTO':
['Annual International Cryptology Conference (CRYPTO)',
'International Conference on the Theory and Application of Cryptographic Techniques (EUROCRYPT)',
'International Conference on the Theory and Application of Cryptology and Information Security (ASIACRYPT)',
'Theory of Cryptography Conference (TCC)',
'Journal of Cryptology',
'International Conference on Theory and Practice of Public Key Cryptography (PKC)',
'IACR Transactions on Symmetric Cryptology (ToSC)',
'International Conference on Applied Cryptography and Network Security (ACNS)',
'Financial Cryptography and Data Security (FC)',
"The Cryptographer's Track at RSA Conference (CT-RSA)",
'Selected Areas in Cryptography (SAC)',
'Conference on Cryptographic Hardware and Embedded Systems (CHES)',
'International Conference on Security and Cryptography for Networks (SCN)',
'IACR Transactions on Cryptographic Hardware and Embedded Systems (TCHES)',
'Fast Software Encryption Workshop (FSE)',
'Designs, Codes and Cryptography',
'International Conference on Cryptology in India (INDOCRYPT)',
'Post-Quantum Cryptography (PQCrypto)',
'International Conference on Information Security and Cryptology (ICISC)',
'Journal of Mathematical Cryptology',
'Information-Theoretic Cryptography (ITC)',
'International Conference on Cryptology in Africa (AFRICACRYPT)',
'Cryptology and Network Security (CANS)',
'International Conference on Cryptology and Information Security in Latin America (LATINCRYPT)',
'IMA Conference on Cryptography and Coding (IMACC)',
'Cryptography',
'Workshop on Encrypted Computing & Applied Homomorphic Cryptography (WAHC)',
'Theory of Quantum Computation, Communication, and Cryptography (TQC)',
'Information Security and Cryptography',
'Journal of Cryptographic Engineering',
'International Conference on Advanced Encryption Standard (AES)',
'Cryptography and Lattices (CaLC)',
'Cryptologia',
'NIST Lightweight Cryptography competition',
'International Workshop on Coding and Cryptography (WCC)'],

'THEORY':
 ['Symposium on the Theory of Computing (STOC)',
'IEEE Annual Symposium on Foundations of Computer Science (FOCS)',
'Innovations in Theoretical Computer Science (ITCS)',
'International Colloquium on Automata, Languages and Programming (ICALP)',
'ACM-SIAM Symposium on Discrete Algorithms (SODA)',
'Theoretical Computer Science',
'ACM/IEEE Symposium on Logic in Computer Science (LICS)',
'Computational Complexity',
'Computational Complexity Conference (CCC)',
'Electronic Colloquium on Computational Complexity (ECCC)',
'Symposium on Theoretical Aspects of Computer Science (STACS)',
'Journal of Algorithms',
'Random Structures and Algorithms',
'European Symposium on Algorithms (ESA)',
'Algorithmica',
'Algorithmic Number Theory Symposium (ANTS)',
'ACM Transactions on Computation Theory (ToCT)',
'Theory of Computing',
'Journal of Complexity',
'IEEE Symposium on Computer Arithmetic (ARITH)',
'Quantum Information & Computation',
'Quantum',
'ACM Transactions on Algorithms (TALG)',
'Foundations and Trends in Theoretical Computer Science',
'Theory of Computing Systems',
'Complexity',
'Discrete & Computational Geometry',
'Algorithms',
'Latin American Symposium on Theoretical Informatics (LATIN)',
],

'SECURITY': ['Annual ACM Conference on Computer and Communications Security (CCS)',
'USENIX Security Symposium',
'IEEE Symposium on Security and Privacy (SP)',
'Network and Distributed System Security Symposium (NDSS)',
'Proceedings on Privacy Enhancing Technologies (PoPETs)',
'European Symposium on Research in Computer Security (ESORICS)',
'European Symposium on Security and Privacy (EuroS&P)',
'International Conference on Cyber Security Cryptography and Machine Learning (CSCML)',
'IEEE Computer Security Foundations Symposium (CSF)',
'Australasian Conference on Information Security and Privacy (ACISP)',
'IEEE Transactions on Dependable and Secure Computing',
'ACM Asia Conference on Computer and Communications Security (AsiaCCS)',
'IEEE Security & Privacy',
'Annual Computer Security Applications Conference (ACSAC)',
'International Conference on Security and Cryptography (SECRYPT)',
'IEEE Transactions on Information Forensics and Security',
'International Workshop on Security (IWSEC)',
'Workshop on Privacy in the Electronic Society (WPES)',
'Journal of Computer Security',
'European Workshop on System Security (EUROSEC)',
'IET Information Security',
'IEEE International Symposium on Hardware Oriented Security and Trust (HOST)',
'IFIP International Information Security Conference (SEC)',
'ACM Transactions on Information and System Security',
'Journal of Privacy and Confidentiality (JPC)',
'International Conference on Information Security Applications (WISA)',
'Cybersecurity',
'Journal of Information Security and Applications',
'Security and Communication Networks',
'Computers & Security',
'Foundations of Security Analysis and Design (FOSAD)',
'Formal Aspects in Security and Trust (FAST)',
'ACM Transactions on Privacy and Security (TOPS)',
'IEEE Conference on Communications and Network Security (CNS)',
'Journal of Information Security',
'Conference on Data and Application Security and Privacy (CODASPY)',
'Journal of Hardware and Systems Security',
'Smart Card Research and Advanced Application Conference (CARDIS)',
'International Conference on Network and System Security (NSS)',
'Nordic Conference on Secure IT Systems (NordSec)',
'Symposium and Bootcamp on the Science of Security (HotSoS)',
'Workshop on Scalable Trusted Computing (STC)',
],

'MATH': ['IEEE Transactions on Information Theory',
'International Symposium on Information Theory (ISIT)',
'Integers',
'SIAM Review',
'Finite Fields and Their Applications',
'SIAM Journal on Discrete Mathematics',
'Discrete Mathematics',
'LMS Journal of Computation and Mathematics',
'Journal of the American Statistical Association',
'Journal of Pure and Applied Algebra',
'Duke Mathematical Journal',
'Mathematical Notes',
'Combinatorica',
'Mathematical Programming',
'IEEE Journal on Selected Areas in Information Theory',
'Studia Logica',
'International Workshop on Arithmetic of Finite Fields (WAIFI)',
'Discrete Applied Mathematics',
'Coding Theory and Applications',
'Journal of Automated Reasoning',
'Communications in Algebra',
'Information Sciences',
'Journal of Applied Probability',
'ACM Communications in Computer Algebra',
'SIAM Journal on Applied Algebra and Geometry',
'Journal of Graph Theory',
'ACM Transactions on Mathematical Software (TOMS)',
'Journal of Statistical Theory and Applications (JSTA)',
'Linear and Multilinear Algebra',
'Journal of Algebra',
'International Symposium on Information Theory and its Applications (ISITA)',
'Journal of Combinatorial Theory',
'Journal of the London Mathematical Society'],

'AI, ML, CV, and Graphics':[
'Conference on Neural Information Processing Systems (NeurIPS)',
'International Conference on Learning Representations (ICLR)',
'International Conference on Machine Learning and Computing (ICMLC)',
'Computer Vision and Pattern Recognition (CVPR)',
'AAAI Conference on Artificial Intelligence (AAAI)',
'International Conference on Machine Learning (ICML)',
'Journal of Machine Learning Research (JMLR)',
'IEEE Transactions on Image Processing',
'IEEE International Conference on Computer Vision (ICCV)',
'Computational Statistics',
'European Conference on Computer Vision (ECCV)',
'British Machine Vision Conference (BMVC)',
'International Joint Conference on Artificial Intelligence (IJCAI)',
'Quantum Machine Intelligence',
'Journal of Symbolic Computation (JSC)',
'International Symposium on Symbolic and Algebraic Computation (ISSAC)',
'Symposium on Symbolic and Algebraic Manipulation (SYMSAC)',
'Journal of Computational and Graphical Statistics (JCGS)',
'ACM Transactions on Graphics (TOG)',
],

'Systems':[
'ACM Symposium on Principles of Distributed Computing (PODC)',
'Symposium on Operating Systems Principles (SOSP)',
'International Systems and Storage Conference (SYSTOR)',
'Symposium on Networked Systems Design and Implementation (NSDI)',
'USENIX Symposium on Operating Systems Design and Implementation (OSDI)',
'IEEE International Conference on Distributed Computing Systems (ICDCS)',
'International Conference on Principles of Distributed Systems (OPODIS)',
'IEEE Transactions on Cloud Computing',
'ACM Symposium on Parallelism in Algorithms and Architectures (SPAA)',
'Distributed Computing',
'USENIX Annual Technical Conference (USENIX ATC)',
'Asia Pacific Workshop on Systems (APSys)',
'IEEE International Conference on Blockchain and Cryptocurrency (ICBC)',
'Allerton Conference on Communication, Control, and Computing (Allerton)',
'IEEE Transactions on Parallel and Distributed Systems (TPDS)',
'International Symposium on Distributed Computing (DISC)',
'IEEE Cloud Computing',
'The Web Conference (WWW)',
'International Symposium on Information Processing in Sensor Networks (IPSN)',
'Annual International Conference on Mobile Computing and Networking (MobiCom)',
'International Conference on Internet of Things (ICIOT)',
'ACM International Conference on Embedded Networked Sensor Systems (SenSys)',
'Computer Networks',
'Journal of Network and Computer Applications',
'European Conference on Computer Systems (EuroSys)',
'IEEE Internet of Things Journal',
'International Conference on Internet Computing (ICOMP)',
'ACM/SIGCOMM Internet Measurement Conference (IMC)',
'Operating Systems',
'Parallel Processing Letters',
'International Conference on Fog Computing (ICFC)',
'IEEE International Conference on Peer-to-Peer Computing',
'International Conference on Parallel Processing (ICPP)',
'Journal of Systems Architecture (JSA)',
'Future Generation Computer Systems',
'SIGOPS European Workshop (SIGOPS)',
'Computing Systems',
],

'Hardware':[
'International Conference on Information, Communications and Signal Processing (ICICS)',
'IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems',
'IET Circuits, Devices & Systems',
'Design Automation Conference (DAC)',
'International Conference on Computer Aided Design (ICCAD)',
'Design, Automation, and Test in Europe (DATE)',
'Formal Methods in System Design',
'IEICE Transactions on Fundamentals of Electronics, Communications and Computer Sciences',
'Foundations and Trends in Electronic Design Automation',
'International Workshop on Signal Design and Its Applications in Communications (IWSDA)',
'International Conference on Computer Design (CDES)',
'VLSI Design',
'IEEE Micro',
'Journal of Electronic Testing',
'Great Lakes Symposium on VLSI (GLSVLSI)',
],

'Software Engineering':[
'ACM-SIGACT Symposium on Principles of Programming Languages (POPL)',
'International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS)',
'ACM Transactions on Programming Languages and Systems (TOPLAS)',
'Proceedings of the ACM on Programming Languages',
'IEEE Software',
'International Conference on Computer Aided Verification (CAV)',
'ACM-SIGPLAN Symposium on Programming Language Design and Implementation (PLDI)',
'ACM SIGPLAN International Conference on Functional Programming (ICFP)',
],

'Database and Information Systems':[
'Very Large Data Bases Conference (VLDB)',
'ACM SIGACT-SIGMOD-SIGART Symposium on Principles of Database Systems (PODS)',
'IEEE Transactions on Knowledge and Data Engineering',
'Data Mining and Knowledge Discovery',
'Annual International ACM SIGIR Conference on Research and Development in Information Retrieval (SIGIR)',
'ACM SIGKDD Conference on Knowledge Discovery and Data Mining (KDD)',
'Big Data',
'IEEE International Conference on Data Engineering (ICDE)',
'ACM Transactions on Database Systems (TODS)',
'Journal of Big Data',
'International Conference on Database Theory (ICDT)',
'Future Internet',
'ACM Conference on Recommender Systems (RecSys)',
'ACM SIGMOD Conference (SIGMOD)',
'Quantum Information Processing',
'International Conference on Information',
'Entropy',
'International Conference on Ubiquitous Information Management and Communication (IMCOM)',],

'Human-centered Computing': ['New Media & Society',
'ACM International Conference on Future Energy Systems (e-Energy)',
'ACM SIGCAS Conference on Computing and Sustainable Societies (COMPASS)',
'Symposium on Computer Science and Law (CSLAW)',
'Computer Law & Security Review (CLSR)',
'ACM SIGCSE Bulletin',
'Human-Computer Interaction'],

'General and Reference': ['SIAM Journal on Computing',
'Communications of the ACM',
'IEEE Access',
'SN Computer Science',
'IEEE Transactions on Computers',
'Computer Science',
'ACM Transactions on Computer Systems (TOCS)',
'ACM Computing Surveys',
'Computers',
'The Computer Journal',
'ACM International Conference on Computing Frontiers (CF)',
'Computing',
'Information Processing Letters',
'Information and Computation',
'Journal of Computer and System Sciences (JCSS)',
'Journal of the ACM',
'IEEE Transactions on Emerging Topics in Computing'],

'Applied Computing':[
'Computers & Geosciences',
'Physical Review Letters',
'Technometrics',
'Scientometrics',
'NASA Formal Methods (NFM)',
'Science',
'Nature',
'Patterns',
'Scientific Reports',
'IEEE Transactions on Services Computing',
'Operational Research',
'Conference on Advances in Financial Technologies (AFT)',
'ACM Digital Rights Management Workshop',
'Journal of Medical Systems',
'NeuroImage',
'Games and Economic Behavior',
'IEEE Transactions on Smart Grid (TSG)',
'IEEE Transactions on Vehicular Technology',
'Bioinformatics',
'BMC Medical Informatics & Decision Making',
],

'Preprints': [
'arXiv',
'ePrint',
],

'Web' : [
'web'
],

'Non-Research Paper':[
'GitHub',
'Tech. Rep.',
'PhD Thesis',
'NIST Submission',
'web_forum',
'Cambridge University Press',
'Technological Standards and Reports',
'Tech. Rep. National',
'IETF Draft',
'Whitepaper',
'Cambridge university press',
'SIGACT News',
],

'UNGROUPED': [
'Communications and Computer Sciences',
'SIGMETRICS Performance Evaluation Review',
'Bell Labs Technical Journal',
'IEEE Communications Surveys and Tutorials',
'ACM SIGPLAN Notices',
'Applied Soft Computing',
'Proceedings of the ACM on Measurement and Analysis of Computing Systems (POMACS)',
'Information',
'AFIPS National Computer Conferences (AFIPS NCC)',
'Phonetica',
'Oxford University Press',
'Devices & Systems',
'Kybernetika',
'IT Professional',
'Tech. Rep. SRI-CSL-98',
'IEEE Communications Letters',
'NIST SHA-3 Competition',
'Wiley',
'Acta Informatica',
'JSIAM Letters',
'Integration',
'IEEE Journal of Selected Areas in Communications']}

print(venueGroupings)